import {createClient} from 'npm:@supabase/supabase-js@2'
import {corsHeaders,jsonResponse} from '../_shared/cors.ts'
import {readCache,writeCache} from '../_shared/cache.ts'
import {FetchProviderClient,requireSecret,sha256Hex} from '../_shared/provider.ts'
import {normalizeOsmElement} from '../_shared/osmNormalize.ts'
import {upsertPlaces} from '../_shared/placeStore.ts'
type Bounds={south:number;west:number;north:number;east:number};type Body={bbox?:Bounds}
function areaKm2({south,west,north,east}:Bounds){const h=Math.abs(north-south)*111.32,w=Math.abs(east-west)*111.32*Math.cos(((north+south)/2)*Math.PI/180);return h*w}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(req.method!=='POST')return jsonResponse({error:'Method not allowed'},405);try{const body=await req.json() as Body;const box=body.bbox;if(!box||[box.south,box.west,box.north,box.east].some(v=>typeof v!=='number'))return jsonResponse({error:'Invalid viewport'},400);const maxArea=Number(Deno.env.get('PLACE_DISCOVERY_MAX_AREA_KM2')??'75');if(areaKm2(box)>maxArea)return jsonResponse({error:'Viewport too large'},400);const base=requireSecret('PLACE_DISCOVERY_PROVIDER_URL'),agent=requireSecret('PLACE_PROVIDER_USER_AGENT');const supabase=createClient(requireSecret('SUPABASE_URL'),requireSecret('SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false}});const rounded={south:+box.south.toFixed(3),west:+box.west.toFixed(3),north:+box.north.toFixed(3),east:+box.east.toFixed(3)};const cacheKey=`place-discovery:${await sha256Hex(JSON.stringify(rounded))}`;const cached=await readCache(supabase,cacheKey);if(cached)return jsonResponse(cached);const query=`[out:json][timeout:20];(nwr[amenity](${box.south},${box.west},${box.north},${box.east});nwr[leisure](${box.south},${box.west},${box.north},${box.east});nwr[tourism](${box.south},${box.west},${box.north},${box.east}););out center tags 250;`;const raw=await new FetchProviderClient().fetchJson<{elements?:Record<string,unknown>[]}>({url:base,method:'POST',headers:{'User-Agent':agent,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({data:query})});const normalized=(raw.elements??[]).map(normalizeOsmElement).filter((x):x is NonNullable<typeof x>=>x!==null);const results=await upsertPlaces(supabase,normalized);const response={results};await writeCache(supabase,cacheKey,'place-discovery',response,21600);return jsonResponse(response)}catch(error){console.error(error);return jsonResponse({error:'Discovery provider unavailable'},503)}})
