import type {ExternalPlace} from './provider.ts'
const allowedTypes=new Set(['node','way','relation'])
const categoryKeys=['amenity','leisure','shop','tourism'] as const
function category(tags:Record<string,unknown>){for(const key of categoryKeys){const v=tags[key];if(typeof v==='string'&&v)return v}return null}
function address(tags:Record<string,unknown>){const full=tags['addr:full'];if(typeof full==='string'&&full)return full;const pieces=['addr:housenumber','addr:street','addr:postcode','addr:city'].map(k=>tags[k]).filter((v):v is string=>typeof v==='string'&&v.length>0);return pieces.length?pieces.join(' '):null}
function stringTags(tags:Record<string,unknown>):Record<string,string>{return Object.fromEntries(Object.entries(tags).filter((entry):entry is [string,string]=>typeof entry[1]==='string'))}
export function normalizeNominatim(row:Record<string,unknown>):ExternalPlace|null{const lat=Number(row.lat),lng=Number(row.lon),display=typeof row.display_name==='string'?row.display_name:null;const rawType=typeof row.osm_type==='string'?row.osm_type.toLowerCase():'';const sourceType=rawType==='n'?'node':rawType==='w'?'way':rawType==='r'?'relation':rawType;if(!allowedTypes.has(sourceType))return null;const sourceId=row.osm_id==null?null:String(row.osm_id);if(!Number.isFinite(lat)||!Number.isFinite(lng)||!sourceId)return null;const name=typeof row.name==='string'&&row.name.trim()?row.name.trim():display?.split(',')[0]?.trim();if(!name)return null;return{source:'osm',sourceType:sourceType as ExternalPlace['sourceType'],sourceId,name,category:typeof row.type==='string'?row.type:null,address:display,lat,lng,sourceTags:stringTags({class:row.class,type:row.type})}}
export function normalizeOsmElement(row:Record<string,unknown>):ExternalPlace|null{const tags=(row.tags&&typeof row.tags==='object'?row.tags:{}) as Record<string,unknown>;const center=(row.center&&typeof row.center==='object'?row.center:{}) as Record<string,unknown>;const lat=Number(row.lat??center.lat),lng=Number(row.lon??center.lon),sourceType=typeof row.type==='string'?row.type:'';const sourceId=row.id==null?null:String(row.id),name=typeof tags.name==='string'?tags.name.trim():'';if(!Number.isFinite(lat)||!Number.isFinite(lng)||!allowedTypes.has(sourceType)||!sourceId||!name)return null;return{source:'osm',sourceType:sourceType as ExternalPlace['sourceType'],sourceId,name,category:category(tags),address:address(tags),lat,lng,sourceTags:stringTags(tags)}}
export const normalizeOverpassElement=normalizeOsmElement
