import { useMemo,useState,type FormEvent } from 'react'
import { useTranslation } from 'react-i18next'
import { parseNeedQuery } from '../needs/needQueryParser'
import type { PlaceFilters } from '../needs/types'
import { searchPlace } from './searchService'
import { SearchResults } from './SearchResults'
import type { ExternalSearchPlace,SearchBias } from './types'
const chipKeys:Array<[keyof PlaceFilters,string]>=[['category','filter.category'],['maxNoise','filter.lowNoise'],['maxCrowding','filter.lowCrowding'],['lighting','filter.softLighting'],['needsToilet','filter.toilet'],['needsSeating','filter.seating'],['needsQuietArea','filter.quietArea'],['needsStepFree','filter.stepFree']]
export function SearchBox({bias,onSelect,onFiltersChange}:{bias?:SearchBias;onSelect:(p:ExternalSearchPlace)=>void;onFiltersChange?:(f:PlaceFilters)=>void}){const {t,i18n}=useTranslation();const [query,setQuery]=useState(''),[results,setResults]=useState<ExternalSearchPlace[]>([]),[filters,setFilters]=useState<PlaceFilters>({}),[status,setStatus]=useState<'idle'|'loading'|'error'>('idle');const locale:'nn'|'en'=i18n.resolvedLanguage?.startsWith('nn')?'nn':'en';const chips=useMemo(()=>chipKeys.filter(([k])=>filters[k]!==undefined),[filters]);const submit=async(e:FormEvent)=>{e.preventDefault();const q=query.trim();if(q.length<2)return;const parsed=parseNeedQuery(q,locale);setFilters(parsed.filters);onFiltersChange?.(parsed.filters);const remote=parsed.recognizedTerms.length?parsed.unmatchedText:q;if(remote.length<2){setResults([]);setStatus('idle');return}setStatus('loading');try{setResults(await searchPlace(remote,locale,bias));setStatus('idle')}catch{setStatus('error')}};return <div className="search-area"><form className="search-box" role="search" onSubmit={submit}><label className="sr-only" htmlFor="sensemap-search">{t('search.placeholder')}</label><input id="sensemap-search" type="search" value={query} onChange={e=>setQuery(e.currentTarget.value)} placeholder={t('search.placeholder')} autoComplete="off"/><button type="submit">{t('search.submit')}</button></form>{chips.length?<div className="filter-chips" aria-label={t('filter.active')}>{chips.map(([k,key])=><span className="filter-chip" key={k}>{k==='category'&&typeof filters[k]==='string'?t(`category.${filters[k]}`,{defaultValue:String(filters[k])}):t(key)}</span>)}</div>:null}{status==='loading'?<div role="status" className="search-status">{t('search.loading')}</div>:null}{status==='error'?<div role="alert" className="search-status">{t('search.error')}</div>:null}<SearchResults results={results} onSelect={onSelect}/></div>}
