import {createClient} from 'npm:@supabase/supabase-js@2'
import {corsHeaders,jsonResponse} from '../_shared/cors.ts'
import {readCache,writeCache} from '../_shared/cache.ts'
import {FetchProviderClient,requireSecret,sha256Hex} from '../_shared/provider.ts'
import {claimProviderRequestSlot} from '../_shared/providerRateLimit.ts'
import {normalizeNominatim} from '../_shared/osmNormalize.ts'
import {upsertPlaces} from '../_shared/placeStore.ts'
type Body={query?:string;locale?:'nn'|'en';bias?:{lat:number;lng:number}}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(req.method!=='POST')return jsonResponse({error:'Method not allowed'},405);try{const body=await req.json() as Body;const q=body.query?.trim();if(!q||q.length<2)return jsonResponse({error:'Search query is too short'},400);const base=requireSecret('PLACE_SEARCH_PROVIDER_URL'),agent=requireSecret('PLACE_PROVIDER_USER_AGENT');const supabase=createClient(requireSecret('SUPABASE_URL'),requireSecret('SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false}});const cacheKey=`place-search:${await sha256Hex(JSON.stringify({q,locale:body.locale??'en',bias:body.bias??null}))}`;const cached=await readCache(supabase,cacheKey);if(cached)return jsonResponse(cached);const allowed=await claimProviderRequestSlot(supabase,'nominatim',1000);if(!allowed)return jsonResponse({error:'Search is temporarily busy. Please retry.'},429,{'Retry-After':'1'});const url=new URL(base);url.searchParams.set('q',q);url.searchParams.set('format','jsonv2');url.searchParams.set('addressdetails','1');url.searchParams.set('limit','10');url.searchParams.set('accept-language',body.locale??'en');if(body.bias){url.searchParams.set('viewbox',`${body.bias.lng-.2},${body.bias.lat+.12},${body.bias.lng+.2},${body.bias.lat-.12}`);url.searchParams.set('bounded','0')}const raw=await new FetchProviderClient().fetchJson<Record<string,unknown>[]>({url:url.toString(),headers:{'User-Agent':agent,'Accept':'application/json'}});const normalized=raw.map(normalizeNominatim).filter((x):x is NonNullable<typeof x>=>x!==null);const results=await upsertPlaces(supabase,normalized);const response={results};await writeCache(supabase,cacheKey,'place-search',response,86400);return jsonResponse(response)}catch(error){console.error(error);return jsonResponse({error:'Search provider unavailable'},503)}})
