import { useEffect,useRef,useState } from 'react'
import { Map,Marker,NavigationControl } from 'maplibre-gl'
import { useTranslation } from 'react-i18next'
import type { GeoPoint } from '../../lib/geo'
import { getEnv } from '../../lib/env'
import type { PlaceSummary } from '../places/types'
import { DEFAULT_CENTER,DEFAULT_ZOOM } from './mapConfig'
import { markerKindFor } from './mapMarkers'
export function SenseMap({places,onLocationResolved,onViewportChanged,onPlaceSelected}:{places:PlaceSummary[];onLocationResolved?:(p:GeoPoint)=>void;onViewportChanged?:(p:GeoPoint)=>void;onPlaceSelected?:(id:string)=>void}){const {t}=useTranslation();const container=useRef<HTMLDivElement|null>(null),mapRef=useRef<Map|null>(null),markers=useRef<Marker[]>([]);const [loc,setLoc]=useState<'idle'|'locating'|'denied'|'unavailable'>('idle');useEffect(()=>{if(!container.current)return;const map=new Map({container:container.current,style:getEnv().VITE_MAP_STYLE_URL,center:DEFAULT_CENTER,zoom:DEFAULT_ZOOM,attributionControl:true});map.addControl(new NavigationControl({showCompass:true}),'top-right');map.on('moveend',()=>{const c=map.getCenter();onViewportChanged?.({lat:c.lat,lng:c.lng})});mapRef.current=map;return()=>{markers.current.forEach(m=>m.remove());markers.current=[];mapRef.current=null;map.remove()}},[onViewportChanged]);useEffect(()=>{const map=mapRef.current;if(!map)return;markers.current.forEach(m=>m.remove());markers.current=places.map(p=>{const kind=markerKindFor(p),el=document.createElement('button');el.type='button';el.className=`sense-marker sense-marker--${kind}`;el.dataset.markerKind=kind;el.setAttribute('aria-label',`${p.name}: ${t(`map.marker.${kind}`)}`);el.title=p.name;el.addEventListener('click',()=>onPlaceSelected?.(p.id));return new Marker({element:el,anchor:'center'}).setLngLat([p.longitude,p.latitude]).addTo(map)});return()=>{markers.current.forEach(m=>m.remove());markers.current=[]}},[places,onPlaceSelected,t]);const locate=()=>{if(!navigator.geolocation){setLoc('unavailable');return}setLoc('locating');navigator.geolocation.getCurrentPosition(({coords})=>{const p={lat:coords.latitude,lng:coords.longitude};setLoc('idle');mapRef.current?.easeTo({center:[p.lng,p.lat],zoom:Math.max(mapRef.current.getZoom(),14)});onLocationResolved?.(p)},e=>setLoc(e.code===e.PERMISSION_DENIED?'denied':'unavailable'),{enableHighAccuracy:false,timeout:10_000,maximumAge:60_000})};const status=loc==='locating'?'map.locating':loc==='denied'?'map.locationDenied':loc==='unavailable'?'map.locationUnavailable':null;return <div className="sense-map-wrap"><div ref={container} className="sense-map" aria-label={t('map.ariaLabel')}/><button type="button" className="map-locate-button" onClick={locate} disabled={loc==='locating'}>{t('map.locate')}</button>{status?<div className="map-location-status" role="status">{t(status)}</div>:null}</div>}
