import { requireContributorSession } from '../auth/auth'
import { supabase } from '../../lib/supabase'
export const moderationReasons=['incorrect_information','offensive_content','spam','personal_information','place_closed'] as const
export type ModerationReason=typeof moderationReasons[number];export type FlagEntityType='place'|'comment'|'sense_report'|'live_report'
export class ModeratorRequiredError extends Error{constructor(){super('Moderator role required');this.name='ModeratorRequiredError'}}
export async function flagContent(input:{entityType:FlagEntityType;entityId:string;reason:ModerationReason;detail?:string}){const s=await requireContributorSession();const {error}=await supabase.from('content_flags').insert({reporter_id:s.user.id,entity_type:input.entityType,entity_id:input.entityId,reason:input.reason,detail:input.detail?.trim()||null});if(error)throw error}
export async function suggestPlaceChange(input:{placeId:string;category:string;present?:boolean;note?:string}){const s=await requireContributorSession();const {error}=await supabase.from('place_change_suggestions').insert({place_id:input.placeId,user_id:s.user.id,payload:{category:input.category,...(input.present===undefined?{}:{present:input.present})},note:input.note?.trim()||null});if(error)throw error}
export interface ModerationQueueItem{id:string;entityType:'comment'|'content_flag'|'place_change_suggestion';entityId:string;status:'pending'|'approved'|'rejected';createdAt:string;placeId:string|null;placeName:string|null;summary:Record<string,unknown>}
async function ensureModerator(){await requireContributorSession();const {data,error}=await supabase.rpc('is_moderator');if(error)throw error;if(data!==true)throw new ModeratorRequiredError()}
async function placeName(id:string|null){if(!id)return null;const {data}=await supabase.from('places').select('name').eq('id',id).maybeSingle();return data?.name??null}
async function flagTarget(type:FlagEntityType,id:string):Promise<{placeId:string|null;target:Record<string,unknown>}>{if(type==='place')return{placeId:id,target:{}};const table=type==='comment'?'comments':type==='sense_report'?'sense_reports':'live_reports';const {data,error}=await supabase.from(table).select('*').eq('id',id).single();if(error)throw error;const row=data as Record<string,unknown>;const placeId=String(row.place_id??'')||null;delete row.user_id;delete row.place_id;return{placeId,target:row}}
export async function listModerationQueue():Promise<ModerationQueueItem[]>{await ensureModerator();const {data,error}=await supabase.from('moderation_items').select('id,entity_type,entity_id,status,created_at').eq('status','pending').order('created_at',{ascending:true});if(error)throw error;return Promise.all((data??[]).map(async row=>{let placeId:string|null=null,summary:Record<string,unknown>={};if(row.entity_type==='content_flag'){const r=await supabase.from('content_flags').select('entity_type,entity_id,reason,detail').eq('id',row.entity_id).single();if(r.error)throw r.error;const target=await flagTarget(r.data.entity_type as FlagEntityType,r.data.entity_id);placeId=target.placeId;summary={reason:r.data.reason,detail:r.data.detail,targetType:r.data.entity_type,target:target.target}}else if(row.entity_type==='place_change_suggestion'){const r=await supabase.from('place_change_suggestions').select('place_id,payload,note').eq('id',row.entity_id).single();if(r.error)throw r.error;placeId=r.data.place_id;summary={...r.data.payload,note:r.data.note}}else{const r=await supabase.from('comments').select('place_id,body').eq('id',row.entity_id).single();if(r.error)throw r.error;placeId=r.data.place_id;summary={body:r.data.body}}return{id:row.id,entityType:row.entity_type,entityId:row.entity_id,status:row.status,createdAt:row.created_at,placeId,placeName:await placeName(placeId),summary}}))}
export async function resolveModerationItem(itemId:string,status:'approved'|'rejected'){await ensureModerator();const {error}=await supabase.rpc('resolve_moderation_item',{p_item_id:itemId,p_status:status});if(error)throw error}
